import requests

def get_chatgpt_response(message):
    """
    Function to get ChatGPT's response using the API (Update with your API details).

    Args:
        message (str): The input message for ChatGPT.

    Returns:
        str: The response generated by ChatGPT.
    """
    chatgpt_api_url = "https://api.openai.com/v1/engines/davinci-codex/completions"
    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer YOUR_CHATGPT_API_KEY",
    }
    data = {
        "prompt": message,
        "max_tokens": 150,
    }
    response = requests.post(chatgpt_api_url, headers=headers, json=data)
    response_json = response.json()
    return response_json["choices"][0]["text"].strip()
